### ISSUE TITLE
Uncaught exception 'Zend_Log_Exception' with message file.log cannot be opened with mode “a”

### ISSUE THREAD

**Issue by mushroom11s** [zendframework/zend-mvc#299] opened 2019-01-02 08:00 UTC
I don't know how to use php, I am developing java.I thought about this error when I deployed a PHP project.

`Fatal error: Uncaught exception 'Zend_Log_Exception' with message '"/home/hystream-apps-test/TOMS/application/../data/log/Ec_Error.log" cannot be opened with mode "a"' in /home/hystream-apps-test/TOMS/libs/Zend/Log/Writer/Stream.php:81 Stack trace: #0 /home/hystream-apps-test/TOMS/libs/Ec/Bootstrap.php(36): Zend_Log_Writer_Stream->__construct('/home/hystream-...') #1 /home/hystream-apps-test/TOMS/libs/Zend/Application/Bootstrap/BootstrapAbstract.php(669): Bootstrap->_initLogging() #2 /home/hystream-apps-test/TOMS/libs/Zend/Application/Bootstrap/BootstrapAbstract.php(622): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('logging') #3 /home/hystream-apps-test/TOMS/libs/Zend/Application/Bootstrap/BootstrapAbstract.php(586): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap(NULL) #4 /home/hystream-apps-test/TOMS/libs/Zend/Application.php(362): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL) #5 /home/hystream-apps-test/TOMS/public/index.php(110): Zend_Application->bootstrap() #6 {main} thr in /home/hystream-apps-test/TOMS/libs/Zend/Log/Writer/Stream.php on line 81`

**Comment by Ocramius** [comment] 2019-01-02 08:00
Duplicate of https://github.com/zendframework/zend-log/issues/95

**Closed as completed by Ocramius** 2019-01-02 08:00 UTC
