### ISSUE TITLE
Deprecated error. Need a quick solution please!

### ISSUE THREAD

**Issue by xLeonius** [zendframework/zend-mvc#103] opened 2016-03-17 18:07 UTC
I have been searching for a solution to this issue for 3 days and I couldn't find an appropriate solution. Every time I get the same Issue, it just says deprecated. Here is what I get on my website:

Deprecated: ServiceManagerAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceManagerAwareInitializer. Please update your class SmallUser\Service\User to remove the implementation, and start injecting your dependencies via factory instead. in C:\Apache24\htdocs\pserverCMSFull\vendor\zendframework\zend-mvc\src\Service\ServiceManagerConfig.php on line 123

Deprecated: You are retrieving the service locator from within the class PServerCore\Controller\IndexController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections. in C:\Apache24\htdocs\pserverCMSFull\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php on line 258

Deprecated: ServiceManagerAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceManagerAwareInitializer. Please update your class PServerCore\Service\News to remove the implementation, and start injecting your dependencies via factory instead. in C:\Apache24\htdocs\pserverCMSFull\vendor\zendframework\zend-mvc\src\Service\ServiceManagerConfig.php on line 123

Deprecated: ServiceManagerAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceManagerAwareInitializer. Please update your class PServerCore\Service\ConfigRead to remove the implementation, and start injecting your dependencies via factory instead. in C:\Apache24\htdocs\pserverCMSFull\vendor\zendframework\zend-mvc\src\Service\ServiceManagerConfig.php on line 123
<
What I tried:
- Tried to remove the error reporting part from the .php files which cause these errors.
- Tried to re-download the whole zend-mvc folder from github, didn't work.

Please keep in mind that I am not an expert in such things, so please give me detailed steps to fix this issue. I'd really be grateful ;)

**Comment by weierophinney** [comment] 2016-03-17 18:26
I've addressed this before in #89, in [a comment](https://github.com/zendframework/zend-mvc/issues/89#issuecomment-191404454). Essentially, we're deprecating the usage of `getServiceLocator()` for the upcoming version 3, and providing you with deprecation notices whenever you use that method from a controller.

There are a few solutions:
- In your `error_reporting`, disable `E_USER_DEPRECATED` reporting. This just masks the problem.
- Pin to an earlier version of zend-mvc (e.g., `composer require "zendframework/zend-mvc:~2.6.0"` will pin specifically to the 2.6 series, and will not install the 2.7 series). This, again, just masks the problem, and will potentially leave your application insecure if security patches are applied to a later minor release of zend-mvc.
- Fix your code to no longer use `getServiceLocator()`. _This is the recommended path._

The way to accomplish this latter point is to ensure that all dependencies for your controller are injected during instantiation. This will mean:
- You need to create factories for your controllers.
- You will need to update your controllers to accept dependencies in their constructors that were previously pulled from `getServiceLocator()`.

As an example, let's say you had something like this in your controller:

``` php
$db = $this->getServiceLocator()->get('Db\ApplicationAdapter');
```

You would change your code as follows:
- Add a `$db` property to your class.
- Update your constructor to accept the database adapter, and assign it to the property.
- Change the above line to simply `$db = $this->db` (or just use the property!)
- Add a factory for your controller, if one does not currently exist.

So:

``` php
use Zend\Db\Adapter\AdapterInterface;
use Zend\Mvc\Controller\AbstractActionController;

class YourController extends AbstractActionController
{
    private $db;

    public function __construct(AdapterInterface $db)
    {
        $this->db = $db;
    }

    public function someAction()
    {
        $results = $this->db->query(/* ... */);
        /* ... */
    }
}
```

Your factory would look something like this:

``` php

class YourControllerFactory
{
    public function __invoke($container)
    {
        return new YourController($this->get('Db\ApplicationAdapter'));
    }
}
```

In your application or module configuration, you would map this factory to your controller:

``` php
return [
    'controllers' => [
        'factories' => [
            YourController::class => YourControllerFactory::class,
        /* ... */
        ],
        /* ... */
    ],
    /* ... */
];
];
```

This may seem like a lot of steps. However, it ensures your code has no hidden dependencies, improves the testability of your code, and allows you to do cool things like substitute alternatives via configuration.

One frequently asked question we receive is: what about dependencies that are only required _sometimes_, like forms, or a database adapter, etc?

You have two options:
- Split your controller into separate responsibilities, and use the more specific controllers. This way you don't need to inject dependencies that are only used in some actions. (I recommend you start doing this _regardless_, as it helps keep your code more maintainable.)
- Use [lazy services](http://zendframework.github.io/zend-servicemanager/lazy-services/). When you configure these, zend-servicemanager gives you a _proxy_ instance that, on first access, loads the full service. This allows you to delay the most expensive operations until absolutely needed.

Good luck!

**Closed as completed by weierophinney** 2016-03-17 18:26 UTC
Labels: question

**Comment by wagnerjsilva** [comment] 2016-04-28 14:20
What about $this->serviceLocator->get('Error_Logger')?

I seem to be able to do that from the controller without any deprecation messages.

**Comment by Okeanrst** [comment] 2016-04-28 15:23
For example:

in module.config.php

``` php
'controllers' => array(
        'factories' => array(
            'Collection' =>
'OkeanrstBooks\Factory\Controller\CollectionControllerFactory'
        ),
    ),
```

In CollectionControllerFactory:

``` php
class CollectionControllerFactory implements FactoryInterface
{
    public function __invoke(ContainerInterface $container, $name, array
$options = null)
    {
        $parentLocator = $container->getServiceLocator();
        $ErrorLogerService =
$parentLocator->get('Error_Logger');
        return new CollectionController( $ErrorLogerService);
    }

    public function createService(ServiceLocatorInterface $container)
    {
        return $this($container, CollectionController::class);
    }
}
```

in CollectionController:

``` php
public function __construct($ErrorLogerService)
 {
        $this->errorLogerService = $ErrorLogerService;
 }

indexAction()
{
    $this->errorLogerService->log($error);
}
```

or manually in ControllerFactory inject in Controller serviceLocator

2016-04-28 17:20 GMT+03:00 Wagner Silva notifications@github.com:

**Comment by weierophinney** [comment] 2016-05-23 18:15
@wagnerjsilva —

> What about `$this->serviceLocator->get('Error_Logger')`?
> 
> I seem to be able to do that from the controller without any deprecation messages.

Don't do that.

Why? Because once you update to zend-servicemanager v3, and zend-mvc v3, the property not only is not injected, _but does not exist_. Follow the instructions from my previous comment.

**Comment by wagnerjsilva** [comment] 2016-05-23 19:19
Probably good idea to add a deprecation message there too.

I've always used the service manager to prevent objects being instantiated multiple times. 

Will the new approach give us any sort of functionality as Zend 1 Zend_Registry? 

`
class YourControllerFactory
{
    public function __invoke($container)
    {
        return new YourController($this->get('Db\ApplicationAdapter'));
    }
}`

I can alway check the source code later, but will the get function prevent the object from being instantiated multiple times, or do we need to go to another library to achieve that?

**Comment by weierophinney** [comment] 2016-05-23 19:26
@wagnerjsilva —

Regarding:

> Probably good to add a deprecation message there too.

We can't add deprecation notices for property access; PHP doesn't allow intercepting that.

Regarding:

> I've always used the service manager to prevent objects being instantiated multiple times.

and

> will the get function prevent the object from being instantiated multiple times, or do we need to go to another library to achieve that?

This is and has always been the case; the service manager caches instances after initial creation (unless configuration indicates a particular service is not shared). `get()` will return the same instance on each request.

Regarding:

> Will the new approach give us any sort of functionality as Zend 1 Zend_Registry?

No, because zend-servicemanager never used that approach, and was in fact a rebuke of that approach. `Zend_Registry` was a global singleton, which is an anti-pattern (makes testing difficult, hides dependencies). zend-servicemanager was intended to address the short-comings of that class. However, by defining `ServiceLocatorAwareInterface` and recommending usage of `getServiceLocator()`, we were still falling prey to many of the same problems. The current deprecation for v3 finally addresses those definitively.

**Comment by wagnerjsilva** [comment] 2016-05-23 19:39
Nice! Thanks for clearing that up.

**Comment by gavinlimely** [comment] 2016-06-13 22:08
Hi @weierophinney, thanks for clearing this up.. Just to clarify, say I have a UsersController that has 5 actions, but only one of the actions requires a dependency, is there any way for me to load the dependency for just that one action? Or do I need to add it to the constructor so it can potentially be used by all of the actions (even though it's not needed).

Cheers

**Comment by michalbundyra** [comment] 2016-06-13 22:19
@gavinlimely there are two approaches described in [documentation](http://zendframework.github.io/zend-mvc/migration/to-v2-7/#optional-dependencies)

**Comment by gavinlimely** [comment] 2016-06-14 09:07
thank you for the quick reply @webimpress, is there any documentation you know of that uses this in controller context?

**Comment by ThaDafinser** [comment] 2016-08-12 07:30
Since ZF is one of the best customizable framework, you can of course "avoid" this deprecation issue for some time...
But please be aware that **_this workaround MUST be a TEMPORARY solution**_
It will not prevent you from correcting your code at the end to upgrade to v3

Use the `application.config.php` to avoid the log messages from ServiceLocator
https://gist.github.com/ThaDafinser/9cb57e0ca70c6fe830bc52f94f14535b#file-application-config-php

And for the controller part, you need all other files
https://gist.github.com/ThaDafinser/9cb57e0ca70c6fe830bc52f94f14535b
