### ISSUE TITLE
AJAX + Forward plugin return 500 Internal Server Error

### ISSUE THREAD

**Issue by popovserhii** [zendframework/zend-mvc#140] opened 2016-05-23 17:16 UTC
I try to call chain of forward plugin in my action through ajax request for get only needed html content but in response return 500 error (in logs nothing).

I have two actions

``` php
public function oneAction()
{
    $request = $this->getRequest();
    $route = $this->getEvent()->getRouteMatch();
    $params = $route->getParams();

    $view = (new ViewModel())->setTerminal($request->isXmlHttpRequest());

    $params['action'] = 'two';
    $viewVm = $this->forward()->dispatch($route->getParam('controller'), $params);
    $view->addChild($viewVm, $params['action']);

    return $view;
}

public function twoAction()
{
    $request = $this->getRequest();
    $view = (new ViewModel())->setTerminal($request->isXmlHttpRequest());

    return $view;
}
```

 and relative templates

``` php
// module/controller/one.phtml
<div>Test one</div>
```

``` php
// module/controller/two.phtml
<div>Test two</div>
```

This is how I send ajax request through firefox http://screencast.com/t/dYwuyPDm

**Comment by michalbundyra** [comment] 2016-05-26 23:41
Not sure if this bug is reported in proper repository. It is caused by:
https://github.com/zendframework/zend-view/blob/master/src/View.php#L232-L234
(when child model is terminated - `setTerminal(true)`).

When you comment out above lines in `Zend\View\View.php` it's gonna work as expected.
I couldn't find anything interesting in tests to understand why we need throw an exception in that case - there is only one test:
https://github.com/zendframework/zend-view/blob/master/test/ViewTest.php#L156-L169

After removing that condition all other tests pass, so I don't know what is the use case of this code.

**Comment by popovserhii** [comment] 2016-05-27 06:47
@webimpress 
I report this is general `zendframwork` [repostitory](https://github.com/zendframework/zendframework/issues/7708#event-669134199) but I was asked move this issue here

**Comment by weierophinney** [comment] 2016-06-09 19:55
> when child model is terminated - setTerminal(true)

A model marked as "terminal" means that it should be rendered _by itself_, not as a child of another view model. What that means is that somewhere along the line, a view model was marked as terminal, but then added as a child to another view model.

And, in fact, we can see that above, as _both_ actions do the following:

``` php
$view = (new ViewModel())->setTerminal($request->isXmlHttpRequest());
```

And in `oneAction()`, you then also have:

``` php
$view->addChild($viewVm, $params['action']);
```

after forwarding to `twoAction()`.

I'm not entirely sure what you're trying to accomplish; is the final view supposed to contain the markup from both view scripts? or only one?
- If you only want the child, you would just return the view it returns.
- If you want both, you should not mark the child view model as terminal, and you will need to render it within the context of the parent view script (using `echo $this->two;`, as the rendered content will be captured to a value matching the child action, in this case).

**Closed as completed by weierophinney** 2016-06-09 19:55 UTC
Labels: question
