### ISSUE TITLE
http-interop/http-middleware abandoned

### ISSUE THREAD

**Issue by mishbah** [zendframework/zend-mvc#275] opened 2018-03-23 09:51 UTC
If you check this site https://github.com/http-interop/http-middleware
You'll see message

**Note: This repository is deprecated and no longer updated. Please refer to [http-interop/http-server-handler](https://github.com/http-interop/http-server-handler) and [http-interop/http-server-middleware](https://github.com/http-interop/http-server-middleware) instead.**

**Comment by froschdesign** [comment] 2018-03-23 10:06
See: #259

**Comment by froschdesign** [comment] 2018-09-04 09:42
Duplicate of #256

**Closed as completed by froschdesign** 2018-09-04 09:42 UTC
Labels: duplicate
